/*
 * This source file was generated by the Gradle 'init' task
 */
package ghrs

import ghrs.ApiService
import java.net.URLDecoder
import java.nio.charset.StandardCharsets
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {

    @Test
    fun respSearchLimit() {
        val apiService = ApiService()
        val config = Config(
            stars = null,
            languages = mutableListOf("java"),
            terms = mutableListOf("xml"),
            sort = null,
            order = null,
            limit = 33,
            created = null,
            updated = null
        )
        apiService.repoSearch(config)
    }

    @Test
    fun decode() {
        println(URLDecoder.decode("https://api.github.com/search/repositories?q=xml+language%3Ajava+stars%3A%3E%3D300&order=desc&per_page=3", StandardCharsets.UTF_8.toString()))

        println(URLDecoder.decode("https://api.github.com/search/repositories?q=xml+language%3Ajava+stars%3A%3E%3D300+pushed%3A%3E%3D&order=desc&per_page=3", StandardCharsets.UTF_8.toString()))

    }
}
