/*
 * This source file was generated by the Gradle 'init' task
 */
package ghrs

import ghrs.ApiService
import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun appHasAGreeting() {
//        val classUnderTest = App()
//        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }

    @Test
    fun respSearchLimit() {
        val apiService = ApiService()
        val config = Config(
            stars = null,
            languages = mutableListOf("java"),
            terms = mutableListOf("xml"),
            sort = null,
            order = null,
            limit = 33,
            created = null,
            updated = null
        )
        apiService.repoSearch(config)
    }
}
